# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cypress-learning-e2e-build

on:
  push:
    branches: [ learning ]
  pull_request:
    branches: [ learning ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Cypress run
      uses: cypress-io/github-action@v5.0.9
      with:
        browser: chrome
        command: npm run test
    - name: Generate Report
      if: ${{ always() }}
      run: npm run report
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
       name: mocha-report
       path: cypress/reports/mochareports
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
    - name: Post the link to the allure report
      if: always()
      run: echo "https://github.com/twCatalyst/cypress-starter/tree/gh-pages/"${{ github.run_number }}
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
       name: allure-report-with-history
       path: allure-history/${{ github.run_number }}
